### ISSUE TITLE
Wrong Mean Reciprocal Rank calculations

### ISSUE THREAD

**Issue by rulezzzz08** [mquad/sars_tutorial#1]
Mean Reciprocal Rank metric depends on predictions list order, but the function remove_duplicates() from util/metrics.py returns shuffled predictions (since an order of elements in a set is undefined) and therefore we get wrong results after calling mrr().

**Comment by mquad** [comment]
Oh good catch @rulezzzz08 ! I removed the call to `remove_duplicates()` from `mrr()`.
Thank you!

**Comment by rulezzzz08** [comment]
Also, if I understand correctly, FSM results should be sorted in descending order of confidence. However, at the moment this sorting is absent and therefore the value of MRR for this recommender is biased.

**Comment by mquad** [comment]
Hi, not ignoring you. I will take a look at the aforementioned issue asap.

**Comment by mquad** [comment]
Hi @rulezzzz08 , thanks for spotting this issue. It should be fixed now: https://github.com/mquad/sars_tutorial/commit/7744941eb47dd807e76bf3a0fb15bf55a68bae4e
