### ISSUE TITLE
Possible bug in sequence_sequential_evaluation (scrolling accuracy calculation)

### ISSUE THREAD

**Issue by AndreyKoshelev** [mquad/sars_tutorial#2]
Hello!
I've been reading the code while studying session-based recommenders and found these odd lines:
https://github.com/mquad/sars_tutorial/blob/b2e12cd25398ab4fff3b7b6f761b759e34af97e2/util/evaluation.py#L105-L109
The iterator gk is not used in this section, and it probably should be (for shifting "ground truth" and "user profile"). It should probably go in place of 'given_k' inside the 'for' loop:

for gk in range(given_k, len(seq), step):
        if eval_res is None:
            eval_res = evaluate_sequence(recommender, seq, evaluation_functions, user, gk, look_ahead, top_n)
        else:
            eval_res += evaluate_sequence(recommender, seq, evaluation_functions, user, gk, look_ahead, top_n)

Pls correct me if i'm wrong and/or this is intended.

**Comment by mquad** [comment]
Hi, not ignoring you. I will take a look at the aforementioned issue asap.

**Comment by mquad** [comment]
Hi, good catch! I've updated the sequential evaluation in this commit: https://github.com/mquad/sars_tutorial/commit/b9cffab7d5a4dd4a9920ef6d755fd961a58a8b50
